name: X-NUCLEO-IKS01A1 Continuous Integration
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*'
      - '**.md'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '*'
      - '**.md'
      - '**.txt'
jobs:
  spell-check:
    runs-on: ubuntu-latest
    name: Spell check
    steps:
    - uses: actions/checkout@main
    - uses: arduino/actions/libraries/spell-check@master
      with:
        ignore-words-list: "./extras/codespell-ignore-words-list.txt"
  lib_build:
    runs-on: ubuntu-latest
    name: Library compilation
    steps:
    # First of all, clone the repo using the checkout action.
    - name: Checkout
      uses: actions/checkout@main

    - name: Compilation
      id: Compile
      uses: stm32duino/actions/compile-examples@main
      with:
        board-pattern: "NUCLEO_L476RG"
        libraries: "STM32duino LSM6DS0, STM32duino LSM6DS3, STM32duino LIS3MDL, STM32duino HTS221, STM32duino LPS25HB"

    # Use the output from the `Compile` step
    - name: Compilation Errors
      if: failure()
      run: |
        cat ${{ steps.Compile.outputs.compile-result }}
        exit 1